name: Daily News Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write   # allow pushing via GITHUB_TOKEN (optional if you're using a PAT)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # avoid persisting the default GITHUB_TOKEN credentials
          persist-credentials: false
          # instead, use your PAT for checkout (optional)
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python src/main.py --config config.yaml --export sqlite

      - name: Commit and push updated DB
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/headlines.db
          git commit -m "Daily news update" || echo "No changes to commit"
          # point origin at the PAT-backed URL
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
