- name: Commit and push updated DB
  env:
    TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git add data/headlines.db
    git commit -m "🤖 Daily news update" || echo "No changes to commit"
    git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
    git push origin HEAD:main
