name: Daily News Scraper

on:
  schedule:
    - cron: '0 6 * * *'  
  workflow_dispatch:     

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python src/main.py --config config.yaml --export sqlite

      - name: Commit and push updated DB
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/headlines.db
          git commit -m " Daily news update" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
